import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card'
import { CalendarDays, Receipt, Wallet, Stethoscope } from 'lucide-react'

interface Props {
  appointments: { status: string }[]
  billing: { amount: string; status: 'Paid' | 'Pending' }[]
}

export default function SummaryStatsCard({ appointments, billing }: Props) {
  const totalPaid = billing
    .filter((b) => b.status === 'Paid')
    .reduce((acc, b) => acc + parseFloat(b.amount.replace('$', '')), 0)

  const pending = billing.filter((b) => b.status === 'Pending').length

  return (
    <>
      <Card className="hidden lg:block">
        <CardHeader>
          <CardTitle className="text-base font-semibold flex items-center gap-2">
            <CalendarDays className="h-4 w-4 text-muted-foreground" /> Upcoming
            Appointments
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="text-2xl font-bold">{appointments.length}</div>
          <p className="text-xs text-muted-foreground">Scheduled this month</p>
        </CardContent>
      </Card>
      <Card>
        <CardHeader className="flex flex-row items-center justify-between pb-2">
          <CardTitle className="text-sm font-medium">Total Invoices</CardTitle>
          <Receipt className="h-4 w-4 text-muted-foreground" />
        </CardHeader>
        <CardContent>
          <div className="text-2xl font-bold">{billing.length}</div>
          <p className="text-xs text-muted-foreground">Generated by system</p>
        </CardContent>
      </Card>
      <Card>
        <CardHeader className="flex flex-row items-center justify-between pb-2">
          <CardTitle className="text-sm font-medium">Total Paid</CardTitle>
          <Wallet className="h-4 w-4 text-muted-foreground" />
        </CardHeader>
        <CardContent>
          <div className="text-2xl font-bold">${totalPaid.toFixed(2)}</div>
          <p className="text-xs text-muted-foreground">Already cleared</p>
        </CardContent>
      </Card>
      <Card>
        <CardHeader className="flex flex-row items-center justify-between pb-2">
          <CardTitle className="text-sm font-medium">
            Pending Payments
          </CardTitle>
          <Stethoscope className="h-4 w-4 text-muted-foreground" />
        </CardHeader>
        <CardContent>
          <div className="text-2xl font-bold">{pending}</div>
          <p className="text-xs text-muted-foreground">To be paid</p>
        </CardContent>
      </Card>
    </>
  )
}
